target-version = "py314"
line-length    = 88
extend-exclude = ["mock"]

[format]
indent-style              = "space"
quote-style               = "single"
line-ending               = "lf"
skip-magic-trailing-comma = false

[lint]
select = ["B", "C4", "E", "F", "I", "SIM", "UP", "W"]
ignore = []

[lint.isort]
lines-after-imports     = 2
split-on-trailing-comma = true
combine-as-imports      = true
force-single-line       = false
