name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CACHIX_NAME: hakula

jobs:
  flake-check:
    name: Nix Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cache_prefix: flake-check
          cachix_name: ${{ env.CACHIX_NAME }}
          cachix_skip_push: 'true'

      - name: Run flake check
        run: nix flake check --all-systems

  build:
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.runner }}
    needs: flake-check
    strategy:
      fail-fast: false
      matrix:
        config:
          - id: nixos
            name: server (x86_64-linux, NixOS)
            runner: ubuntu-latest
            target: .#nixosConfigurations.us-4.config.system.build.toplevel
          - id: macos
            name: hakula-macbook (aarch64-darwin, macOS)
            runner: macos-latest
            target: .#darwinConfigurations.hakula-macbook.system
          - id: generic-linux
            name: hakula-work (x86_64-linux, Generic Linux)
            runner: ubuntu-latest
            target: .#homeConfigurations.hakula-work.activationPackage
          - id: docker
            name: hakula-devvm (x86_64-linux, Docker)
            runner: ubuntu-latest
            target: .#packages.x86_64-linux.hakula-devvm-docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cache_prefix: ${{ matrix.config.id }}
          cachix_name: ${{ env.CACHIX_NAME }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          cachix_skip_push: ${{ !(github.ref == 'refs/heads/main' || github.actor == 'hakula139') }}

      - name: Build configuration
        run: |
          nix build ${{ matrix.config.target }} \
            --print-build-logs \
            --show-trace

      - name: Check system closure size
        run: |
          nix path-info -Sh ${{ matrix.config.target }}
