name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CACHIX_NAME: hakula

jobs:
  flake-check:
    name: Nix Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cache_prefix: flake-check
          cachix_name: ${{ env.CACHIX_NAME }}
          cachix_skip_push: 'true'

      - name: Run flake check
        run: nix flake check --all-systems

  build:
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.runner }}
    needs: flake-check
    strategy:
      fail-fast: false
      matrix:
        config:
          - id: nixos
            name: cloudcone-sc2 (x86_64-linux, NixOS)
            runner: ubuntu-latest
            target: .#nixosConfigurations.cloudcone-sc2.config.system.build.toplevel
          - id: generic-linux
            name: hakula-linux (x86_64-linux, Generic Linux)
            runner: ubuntu-latest
            target: .#homeConfigurations.hakula-linux.activationPackage
          - id: macos
            name: hakula-macbook (aarch64-darwin, macOS)
            runner: macos-latest
            target: .#darwinConfigurations.hakula-macbook.system

    steps:
      - name: General cleanup
        if: ${{ runner.os == 'Linux' }}
        run: |
          cleanup() {
            local dir="$1"
            if [ -d "$dir" ]; then
              local size="$(du -sh "$dir" | awk '{print $1}')"
              sudo rm -rf "$dir"
              echo "Cleaned up $dir, size: $size"
            fi
          }

          cleanup /usr/lib/jvm
          cleanup /usr/local/.ghcup
          cleanup /usr/local/share/powershell
          cleanup /usr/share/dotnet
          cleanup /usr/share/swift

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          cache_prefix: ${{ matrix.config.id }}
          cachix_name: ${{ env.CACHIX_NAME }}
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          cachix_skip_push: ${{ github.ref != 'refs/heads/main' }}

      - name: Build configuration
        run: |
          nix build ${{ matrix.config.target }} \
            --print-build-logs \
            --show-trace

      - name: Check system closure size
        run: |
          nix path-info -Sh ${{ matrix.config.target }}
